### PR TITLE
include function inserting asterisks between chars for usability

### PR DESCRIPTION
**Pull request by joelsa**
I have found usability to suffer from the need of having to include an asterisks between each conjunction. Internally inserting an asterisks between to consecutive ASCII chars solves this problem. 26 variables should be enough for all intents and purposes.

### CODE REVIEW

**Comment by NKPmedia** [comment]
Hello please solve merge problems with the actual commit.

I thing the function can't handle this : "a+b(a+b)" at the moment ("a+b(a+b" is the actual result). Can you add this. Also this "a+(a+b)b" should by a correct expression.

**Comment by joelsa** [comment]
Does the current implementation favor conjunction

**Comment by joelsa** [comment]
Does the current implementation prioritize conjunctions over disjunctions? If not, parentheses would have to be added. Example: ab+cd currently becomes a*b+c*d, whereas maybe (a*b)+(c*d) is desired.

**Comment by NKPmedia** [comment]
The system favors disjunctions (*). Like the normal point before line calculation. So ab+cd becomes ((d*c)+(b*a)). You can see that at "Parsed tree".

**Pull request merged**
